version: '3.3'
services:
    aio-erp:
        ports:
            - '${HTTP_PORT:-8080}:80'
        volumes:
            - ./tomcat/data:/var/lib/tomcat
            - ./postgresql/data:/var/lib/postgresql
            - ./tomcat/logs:/var/log/tomcat
            - ./postgresql/logs:/var/log/postgresql
        restart: always
        image: axelor/aio-erp
